project:
  type: website

website:
  title: "Mark Gingrass"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
      - booklist.qmd
    right:
      - icon: github
        href: https://github.com/mtgingrass
        aria-label: GitHub
      - icon: envelope-arrow-up-fill
        href: mailto:mark.gingrass@gmail.com

format:
  html:
    theme: solona
    css: styles.css
    toc: true

editor: visual

freeze: auto

execute:
  freeze: auto

